site_name: 'Sovrin Business Utility Governance Framework'
site_description: 'Sovrin Business Utility Governance Framework.'
site_dir: 'html'

nav:
- Informational:
    - 'Overview': 'index.md'
    - 'Consortium': 'gf_info/consortium.md'
    - 'Motivation': 'gf_info/transition.md'
    - 'Membership': 'gf_info/membership.md'
    - 'Term Sheet': 'gf_info/termsheet.md'
- Constitutional:
    - 'Master Document': 'gf_info/masterdoc.md'
    - 'Glossary': 'gf_info/glossary.md'
    - Controlled:
        - 'Governing Bodies': 'gf_controlled/governing_bodies.md'
        - 'Consortium Bylaws': 'gf_controlled/by_laws.md'
        - 'Governing Body Policies': 'gf_controlled/governing_body_policies.md'
        - 'Ledger Access Policies': 'gf_controlled/ledger_access_policies.md'
        - 'Ledger Data Policies': 'gf_controlled/ledger_data_polices.md'
        - 'Member Business Policies': 'gf_controlled/member_business_policies.md'
        - 'Member Technical and Organizational Policies': 'gf_controlled/member_top.md'
        - 'Endorser Business Policies': 'gf_controlled/endorser_business_policies.md'
        - 'Endorser Technical and Organizational Policies': 'gf_controlled/endorser_top.md'
        - 'Economic Policies': 'gf_controlled/economic_policies.md'
        - 'Certification Mark Policies': 'gf_controlled/certification_mark_policies.md'
        - 'Trust Network Polices': 'gf_controlled/trusted_network_policies.md'
    - Legal:
        - 'Architecture': 'gf_legal/legal_arch.md'
        - 'Trusted Network': 'gf_legal/trusted_network.md'
        - 'Member Agreements': 'gf_legal/member_agreements.md'
        - 'Non-Member Agreements': 'gf_legal/non_member_agreements.md'
- Compliance:
    - 'Trust Assurance': 'gf_assurance/index.md'
- Help:
    - 'FAQ': 'faq.md'
    - 'Contact us': 'contact_us.md'


plugins:
    - search
    - pdf-export:
        verbose: true
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT
        combined: true
        combined_output_path: /usr/share/nginx/sbu-gf.pdf

theme:
    name: 'material'
    custom_dir: 'theme'

extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true


copyright: Copyright &copy; 2020
