apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgfv3
  labels:
    app: sgfv3
spec:
  selector:
    matchLabels:
      app: sgfv3
  template:
    metadata:
      labels:
        app: sgfv3
    spec:
      containers:
      - name: sgfv3
        image: {{.Values.image_name}}
        imagePullPolicy: Always
        ports:
        - name: sgfv3
          containerPort: {{.Values.container_port}}
