apiVersion: v1
kind: Service
metadata:
  name: sgfv3
spec:
  type: LoadBalancer
  selector:
    app: sgfv3
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: {{.Values.container_port}}
